version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static/public:/usr/share/nginx/html:ro
    networks:
      - frontend

  freshrss:
    image: freshrss/freshrss:latest
    # container_name: freshrss
    # restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./freshrss/data:/var/www/FreshRSS/data


networks:
  frontend:
